### PR TITLE
Initial commit, added a readme file

### PR DESCRIPTION
**Pull request by kuhnbt7**

### CODE REVIEW

**Comment by natasha-aleksandrova** [comment]
@kuhnbt7 please make sure to submit your pull request link in each assignment submission on the course website (before moving on to next assignment so we can grade and merge the PR)

**Comment by natasha-aleksandrova** [comment]
still no submission in the course website but merging

**Comment by kuhnbt7** [comment]
Sorry I overlooked that, I'll be sure to submit on the course site in the future

**Comment by natasha-aleksandrova** [comment]
no worries and thank you! 

do submit this PR link:
https://github.com/UWPCE-PythonCert-ClassRepos/Self_Paced-Online/pull/104

retroactively on the website for grid printer, fizzbuzz and series assignments

**Comment by kuhnbt7** [comment]
Will do, thanks. Still getting the hang of github :)

**Comment by natasha-aleksandrova** [comment]
understandable!

**Pull request merged**
