### PR TITLE
Added all of lesson 2

### PR DESCRIPTION
**Pull request by hood821**
finished the exercise, please look at grid_printer.py

### CODE REVIEW

**Comment by hood821** [comment]
Added the Fizzbuzz exercise, please look at fizzbuzz.py

**Comment by hood821** [comment]
Added Series.py, please look at all of lesson 2

**Comment by hood821** [comment]
I don't understand? Did you not look at my assignment?

Tressa

**Comment by hood821** [comment]
Okay so I did everything over again and created a new pull request...

https://github.com/UWPCE-PythonCert-ClassRepos/Self_Paced-Online/pull/1021#issue-221293827


This is what my commands looked like:
[image: image.png]

and here is my remote status...

[image: image.png]

I hope this is correct and it worked this time? I deleted everything and
started over ...

Thanks!
Tressa

**Comment by natasha-aleksandrova** [comment]
@hood821 when you reply via email I cannot see your attachments, it is best to reply directly here on github.

The PR was closed because I couldn't merge it the way it was - there are 4 tabs at the top of this page and the last one has "Files Changed" tab which included 101 files changed (that are not your changes). That was the reason, your repo was out of sync.

I see your new PR and it looks correct.  Please make sure to keep your fork up to date by following commands in the doc I linked, Thanks!

**Pull request closed without merging**
