### PR TITLE
Dustin_L - Lesson02 - Series

### PR DESCRIPTION
**Pull request by rdlaner**
Series assignment.

### CODE REVIEW

**Comment by natasha-aleksandrova** [comment]
@rdlaner code looks good and good tests

to conform to python styling guide I would recommend updating some vars to use `snake_case` not `camelCase` style

**Comment by rdlaner** [comment]
Thanks for the feedback. I will start using `snake_case` going forward.

**Comment by natasha-aleksandrova** [comment]
you can use command line utility like this:
https://github.com/UWPCE-PythonCert-ClassRepos/Self_Paced-Online/pull/38

or IDE like Pycharm which will auto flag the violations for you.

**Comment by rdlaner** [comment]
Yeah, I'm using Visual Studio Code and its Python extension. I just configured it to use pylint and that does catch this style violation. I think that should work well going forward. Thanks!

**Comment by natasha-aleksandrova** [comment]
perfect that should work!

**Pull request merged**
