### PR TITLE
lesson07 - question

### PR DESCRIPTION
**Pull request by JerHsi**
@natasha-aleksandrova , I keep getting AttributeError: 'Element' object has no attribute 'append' even I have "append" class method defined.  Why is that?

### CODE REVIEW

**Comment by natasha-aleksandrova** [comment]
@JerHsi what are you running to get that error?

**Comment by natasha-aleksandrova** [comment]
I ran `run_html_render.py` but got `AttributeError: 'Element' object has no attribute 'render'`

**Comment by JerHsi** [comment]
@natasha-aleksandrova 
This is what I got:
In [133]: %run run_html_render.py
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/Documents/Python/Self_Paced-Online/students/JerryH/Lesson07/run_html_render.py in <module>()
     36 page = hr.Element()
     37 
---> 38 page.append("Here is a paragraph of text -- there could be more of them, "
     39             "but this is enough  to show that we can do some text")
     40 

AttributeError: 'Element' object has no attribute 'append'

**Comment by natasha-aleksandrova** [comment]
Since I'm not getting the same stack trace my only guess is something else is getting imported. Worth trying:
```
page = hr.Element()
print(hr.__file__)
```
after you create instance of Element print module file then open that file and very it is the correct class definition and has your append method

**Comment by JerHsi** [comment]
@natasha-aleksandrova I closed my iPython session and re-opened a new one, and now it works as it should be.  Not quite sure why it didn't work before though.  Thanks anyway.

**Comment by natasha-aleksandrova** [comment]
ah! iPython won't auto pick up changes in your file unless you set a magic variable.

**Comment by JerHsi** [comment]
How should I do that?

**Comment by natasha-aleksandrova** [comment]
follow this guide here:
https://ipython.org/ipython-doc/3/config/extensions/autoreload.html

**Pull request closed without merging**
