### PR TITLE
lesson06 - fixed code to give chance for more tests

### PR DESCRIPTION
**Pull request by ghassan24601**

### CODE REVIEW

**Comment by robalford** [comment]
@natasha-aleksandrova this is ready to merge and regrade the homework submission.

**Comment by robalford** [comment]
@ghassan24601 remember to submit this for grading on the course website.

**Comment by natasha-aleksandrova** [comment]
@ghassan24601 you should be able to resubmit now on the course website, let me know if you're having issues.

**Comment by ghassan24601** [comment]
Thanks for the feedback!
I'm unable to resubmit on the course's website, it shows as cancelled with no place to paste a new link.

**Pull request merged**
