### PR TITLE
Lesson 7

### PR DESCRIPTION
**Pull request by vvinodh**

### CODE REVIEW

**Comment by natasha-aleksandrova** [comment]
@vvinodh did you commit all of the files?

I'm not seeing actual code submitted.

**Comment by vvinodh** [comment]
Is it, I will commit again.

**Comment by vvinodh** [comment]
Natasha,
I added code to github again. Below is a screenshot. Not sure where I am
going wrong. I also attached the code to course site.

**Comment by natasha-aleksandrova** [comment]
@vvinodh instead of replying via email please reply directly on github; your email attached images are not visible on here.

**Comment by vvinodh** [comment]
Hello Natasha, is there a way you can merge https://github.com/UWPCE-PythonCert-ClassRepos/Self_Paced-Online/pull/780

**Comment by natasha-aleksandrova** [comment]
@vvinodh your lesson 8 looks fine and submitted the grade on the course website. keeping open for lesson 7.

**Comment by natasha-aleksandrova** [comment]
merging for lesson8; lesson 7 is incomplete.

**Pull request merged**
