### PR TITLE
lesson3 - mailroom.py

### PR DESCRIPTION
**Pull request by kmsnyde**
Not an easy assignment for; lots of off classroom research where I didn't feel the class documentation helped me to understand and solve the this particular lesson.  Feedback always welcome!

### CODE REVIEW

**Comment by natasha-aleksandrova** [comment]
make sure to submit the assignment on the course website

**Comment by kmsnyde** [comment]
Hi Natasha,

I noticed this part of the lesson (mailroom) did not receive a staff grade.  For clarification, are you waiting for me to implement the changes before grading?  Thanks.

 

 

Regards,
Karl

 

 

-----Original Message-----

**Comment by natasha-aleksandrova** [comment]
@kmsnyde have you submitted the assignment on the course website? I don't see anything pending there.

**Comment by natasha-aleksandrova** [comment]
From what I can see this was submitted recently. I see it now.

**Comment by kmsnyde** [comment]
I submit my class assignment in the classroom at the same time I do the PR.  This is at least the second time I've seen an email from you in an assignment that I've done a PR that you made a note to ensure I submit in the course website.  I have done so each and every time so not sure why there is such a long ((3-4 days) delay before you see it posted in the classroom website.

 

 

Regards,
Karl

 

 

-----Original Message-----

**Comment by natasha-aleksandrova** [comment]
very interesting information. let's see if this happens again on the next assignment and if it does we can reach out to tech support for the course platform.

**Comment by kmsnyde** [comment]
Agreed.  Thanks Natasha.

 

 

Regards,
Karl

 

 

-----Original Message-----

**Comment by kmsnyde** [comment]
Hi Natasha,

In ref to the mailroom part 2 lesson: I did my PR then I uploaded my mailroom part 2 file in the classroom and it is awaiting Staff Grade. 

This is to determine if there is still a latency issue when I upload in the classroom and you can see it, per below conversation.  Thanks.

 

 

Regards,
Karl

 

 

-----Original Message-----

**Pull request merged**
