### PR TITLE
Uplaoded with more refinements

### PR DESCRIPTION
**Pull request by MikeS-1**
Thank you Natasha for your generous donation of 1000!
Please accept our thanks, and this honorary membership in the fruitcake of the month club.

### CODE REVIEW

**Comment by natasha-aleksandrova** [comment]
@MikeS-1 should we only review updates to mailroom switch file and ignore trigram code for now?

**Comment by robalford** [comment]
@MikeS-1 your mailroom revisions look great. The only suggestion I have is that you go ahead and delete the code from the previous version that you have commented out. One of the great things about git, is if you commit your changes, you can always go back and look at the older versions of your code so there's no need to keep old dead code hangin around. 

I don't see a submission for trigrams on the course website yet so Im going to wait to review that one. You can push your work here if you want to keep this open, and let me know by commenting when it's ready to review. Or we can merge this and you can create a new pull request for that assignment. Let me know what works for you.

**Comment by MikeS-1** [comment]
My apologies for the confusion with the Trigrams submission. It was a little bit of a challenge. I've submitted it now for review. First hack, at least.

Will update mail room as well.
Thank you!
________________________________

**Comment by robalford** [comment]
@MikeS-1 no worries about the submission and you're off to a great start with trigrams. 

Your `new_story` function gets close to what the assignment requires but still needs some work. It looks like you are randomly selecting any two word pair in the text, followed by another randomly selected word that is associated with that pair in your book_dict, and then chaining together those selections to form your new text. 

The part that appears to be missing is the key look up for the last two words of your new three word combo. To clarify, using the pseudocode example from the assignment directions, if this were your book_dict:
```
"I wish" => ["I", "I"]
"wish I" => ["may", "might"]
"may I"  => ["wish"]
"I may"  => ["I"]
```
your alogrithm should grab a random key ('wish I'), look up a random value associated with that key ('may') and add those to the new text ('wish I may'). Then your next lookup should take the last two words of the new text ('I may') and look up a value associated with that pair ('I') so you now have
'wish I may I' giving you ('may I') as your next lookup.

A couple other things you may want to consider as you're working on this: you can use a `tuple` for the two word keys in your `book_dict`, and you should check out Python's `list.extend` method for adding all the elements from one list to the end of another.

**Comment by natasha-aleksandrova** [comment]
@MikeS-1 please review Rob's comments/suggestions for trigrams assignment.

I'm going to go ahead and merge this in since there are a lot of other things here. Go ahead and open up a new PR with a finished version of trigrams when you're ready and add a comment referencing this PR so that we know it's the finished version.

Thanks! let us know if you have any other questions.

**Comment by MikeS-1** [comment]
https://github.com/UWPCE-PythonCert-ClassRepos/Self_Paced-Online/pull/285

Here’s my second try. I’m not sure why I keep getting an IndexError. I assumed that I was running out of keys, but making the iterator shorter didn’t seem to fix the problem.

Also, can you help me understand why I would want to extend the list instead of appending the new_word to it?

Thank you!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Pull request merged**
