### PR TITLE
Lesson9

### PR DESCRIPTION
**Pull request by lauraannf**

### CODE REVIEW

**Comment by natasha-aleksandrova** [comment]
Merging this PR - however would like to see objects being actually utilized

**Comment by lauraannf** [comment]
I use Donor on line 50 of mailroom_oo, so then each donor in the donor_list
is a Donor object.
Is this the application you're looking for?

**Comment by natasha-aleksandrova** [comment]
That's exactly it - thank you for pointing that out, not sure how I missed that line.

**Comment by lauraannf** [comment]
Oh good, I was worried that I was doing everything totally wrong!

**Pull request merged**
