### PR TITLE
adding lesson 3 slicing exercise and lesson 2 updates

### PR DESCRIPTION
**Pull request by tfbanks**
Adding lesson 3 Slicing exercise and updates to lesson 2 exercises, I also changed the file fibonacciseries.py to series.py as it was more than just Fibonacci.

I wrote a comment that I can see on the bottom of this request.  I figured out why Lesson 3 wasn't being added (typed lesson03 instead of Lesson03) however I still can't figure out how the read me file from JerryH got in the mix; still can't figure out how that got mixed up in my update.

### CODE REVIEW

**Comment by natasha-aleksandrova** [comment]
@tfbanks could you give me access to your forked repo?

I would like to fix accidentally changed files before merging. Thanks.

If you have further questions reach out to us via email.

**Comment by tfbanks** [comment]
Sure, but how do I do that?  I’m still learning GitHub while working the files.  

Thanks,

Trenton

**Comment by natasha-aleksandrova** [comment]
screen shot 2018-07-24 at 8 14 00 am

on your forked repo, go to Settings > Collaborators and add my user: `natasha-aleksandrova`

then I will be able to clone and push changes to revert your commits.

**Comment by tfbanks** [comment]
Ok, I’ll do it after work today

**Comment by natasha-aleksandrova** [comment]
Ok please run following commands on your master branch:
```
git checkout 3784528a24d223bf4155a0b90ff8247f3e587193^ -- students/JerryH/Lesson02/README.rst
git status
git add students/JerryH/Lesson02/README.rs
git commit -m "readd deleted file"
git push origin master
```

it is always best to run git status and only run `git add .` if you're really comfortable with what you're adding. otherwise `git add <file_path>`

**Comment by tfbanks** [comment]
Thanks for your assistance.  I usually only commit what I want, but since I was spelling the file name wrong (not capitalizing a letter when I needed to) and couldn’t figure out why at that time, I tried a commit all, which brought that comment in. 

I also realized I didn’t comment the code for the slicing exercise, go back from vacation and was trying to get back on track.  

Thanks again. I’ll try running this.  Almost done with the list lab fruit exercise.

**Comment by tfbanks** [comment]
I ran the code.  hope that worked.

**Comment by natasha-aleksandrova** [comment]
@tfbanks I see no new commits.

do you still have the output with commands you ran that you can share?

**Comment by natasha-aleksandrova** [comment]
I ran the same commands last night myself on my own branch in your fork, so you should see a commit similar to mine here:
https://github.com/tfbanks/Self_Paced-Online/commit/039b8f5d752d5ef3058818fe0c328ff430ae454b

**Comment by tfbanks** [comment]
I unfortunately I have anything to compare with now, but what you showed looks right

**Comment by natasha-aleksandrova** [comment]
Ok, I am just going to run those commands myself on your master branch.

**Comment by natasha-aleksandrova** [comment]
```
natasha.aleksandrova@z-mac-1535-Natasha-Aleksandrova:~/Dev/tfbanks_uw/Self_Paced-Online$ git checkout 3784528a24d223bf4155a0b90ff8247f3e587193^ -- students/JerryH/Lesson02/README.rst
natasha.aleksandrova@z-mac-1535-Natasha-Aleksandrova:~/Dev/tfbanks_uw/Self_Paced-Online$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   students/JerryH/Lesson02/README.rst

natasha.aleksandrova@z-mac-1535-Natasha-Aleksandrova:~/Dev/tfbanks_uw/Self_Paced-Online$ git add students/JerryH/Lesson02/README.rs
fatal: pathspec 'students/JerryH/Lesson02/README.rs' did not match any files
natasha.aleksandrova@z-mac-1535-Natasha-Aleksandrova:~/Dev/tfbanks_uw/Self_Paced-Online$ git add students/JerryH/Lesson02/README.rst
natasha.aleksandrova@z-mac-1535-Natasha-Aleksandrova:~/Dev/tfbanks_uw/Self_Paced-Online$ git commit -m "readd deleted file"
[master 26be57b5] readd deleted file
 1 file changed, 1 insertion(+)
 create mode 100644 students/JerryH/Lesson02/README.rst
natasha.aleksandrova@z-mac-1535-Natasha-Aleksandrova:~/Dev/tfbanks_uw/Self_Paced-Online$ git push origin master
Counting objects: 6, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (6/6), 520 bytes | 520.00 KiB/s, done.
Total 6 (delta 4), reused 1 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To github.com:tfbanks/Self_Paced-Online.git
   8067f6b5..26be57b5  master -> master
natasha.aleksandrova@z-mac-1535-Natasha-Aleksandrova:~/Dev/tfbanks_uw/Self_Paced-Online$```

Done, Please make sure to run git pull in your master branch before any further work.

Again, extremely important to observe changes via git status before running git add / git commit and observing output of git commands for errors.

**Pull request merged**
