### PR TITLE
Next shot at trigrams

### PR DESCRIPTION
**Pull request by MikeS-1**
Not sure why I keep getting an IndexError

### CODE REVIEW

**Comment by robalford** [comment]
@MikeS-1 looks good! I believe the IndexError is coming from two word keys in your book dict with empty lists as values because there are no words that follow them in the text sample. I think your try/except block is a fine way to handle this since it's not going to happen every time your parse the text. 

There are still some ways you could simplify things and I'd suggest you take a look at Natasha's solution [here](https://github.com/natasha-aleksandrova/Self_Paced-Online/blob/master/solutions/lesson4/trigrams.py) for some ideas. Please resubmit the assignment on the course website so we can grade it. This PR is ready to merge.

**Comment by MikeS-1** [comment]
Hmm, I can’t figure out how to resubmit on the website. It won’t let me paste an updated link, and doesn’t have the upload options.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by MikeS-1** [comment]
https://github.com/UWPCE-PythonCert-ClassRepos/Self_Paced-Online/pull/285

Cleaned up the string import and resubmitted

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by natasha-aleksandrova** [comment]
@MikeS-1 your submission grade has been adjusted for this lesson.

**Pull request merged**
