### PR TITLE
Assignmnet09

### PR DESCRIPTION
**Pull request by mzkhan87**
Dear Instructor(s), 

Please review my assignment09. I used several classes to organize my code. I also had to do the refactoring to better fit my code where it belongs in the classes. 

I will like your feedback about my method choices--Static, Class or Instance methods. If you have solution for this assignment, please let me know. I'm keen to learn the best design approach to tackle this mailroom problem. 

Thanks.

### CODE REVIEW

**Comment by natasha-aleksandrova** [comment]
@mzkhan87 I took a quick look at your solution and I would recommend reviewing some resources first (below). You have a lot of different inheritance that doesn't necessarily apply here.

Please read guidelines here:
https://uwpce-pythoncert.github.io/PythonCertDevel/exercises/mailroom-oo.html#the-program

Here is an example stub code to get you started:
https://repl.it/@naaleksandrova/Lesson9Example

**Comment by natasha-aleksandrova** [comment]
please let me know if you have any further questions, I will close this for now and please resubmit when you're ready.

**Comment by mzkhan87** [comment]
Thanks Natasha for your detailed feedback. I will fix the code and resubmit
it.

Regards,

Muhammad Khan

**Comment by mzkhan87** [comment]
Hi Natasha,

Per the resources you pointed out, it is asked to use the packages to
structure the code.  Should I just write the code in one file like
"mailroom_oo.py consist of Donor class, Collection class and the functions
associated with UI?. I will also add the test file to test my
functionality. If you'd like me to create the package, I could do so. But I
don't think it will be necessary at this time. Please advise.

[image: image.png]

Thanks.

**Pull request closed without merging**
