### PR TITLE
Added Grid Printer files and Fizz Buzz

### PR DESCRIPTION
**Pull request by vmedina1014**
Added all three parts of the grid printer assignment and the fizz buzz function.

### CODE REVIEW

**Comment by vmedina1014** [comment]
added series.py

**Comment by vmedina1014** [comment]
More formatting changes.

**Comment by vmedina1014** [comment]
Should I wait until after you merge to resubmit the file?

**Comment by charlesrobison** [comment]
No, you can remove the one that needs to be removed, and then submit it in the correct place in this same PR.  If that's too confusing, we can close this PR and you and re-submit everything in a new PR.

**Comment by charlesrobison** [comment]
@vmedina1014 - I'm closing this PR so as to not cause any issues with the class repository.  Please do a new PR and submit your files for review.

**Comment by vmedina1014** [comment]
Sorry Charles I stayed late at work. I created a new pull request. The link
can be found here:
https://github.com/UWPCE-PythonCert-ClassRepos/Self_Paced-Online/pull/1345

**Pull request closed without merging**
